project_name: gantry
builds:
  - binary: gantry
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: osx
    linux: linux
